### ISSUE TITLE
CSS compressor doesn't handle media_urls containing https correctly

### ISSUE THREAD

**Issue by BradWhittington** [mintchaos/django_compressor#12]
Similar to the data: munging that happened, the compressor doesn't gracefully handle https urls.

**Comment by BradWhittington** [comment]
I have fixed this in my fork - http://github.com/bradwhittington/django_compressor/tree/67a074ff9af46c7bbd2a2616b680e03ca288f67e

**Comment by mintchaos** [comment]
Your changes have been merged in.

**Comment by mintchaos** [comment]
Thanks!

**Comment by blueyed** [comment]
This should (probably) support protocol relative URLs, too, like "//example.com/style.css".
(This is relative to the currently supported protocol, like "http" or "https")
