### ISSUE TITLE
CSSTidy filter raises NameError: global name 'css' is not defined

### ISSUE THREAD

**Issue by boralyl** [mintchaos/django_compressor#13]
Setting up my settings like so:
    COMPRESS_CSS_FILTERS = ['compressor.filters.csstidy.CSSTidyFilter']
does not work since css is not defined in the output method of the CSSTidyFilter class.

The fix for this is located at my fork: http://github.com/boralyl/django_compressor/commit/4f8f5a86922c2c25ba929d246b4eb1d78be08840

**Comment by richleland** [comment]
I can confirm this change fixes the issue. Any chance you could merge this into master?

**Comment by jezdez** [comment]
Fixed in 9e148cdd90c61659c2f6e2d8b9172a4342fb63c0.
