### ISSUE TITLE
Don't create empty bundle

### ISSUE THREAD

**Issue by sw** [mintchaos/django_compressor#14]
I'm loading compressor in my base template and then define a JS block like this:

{% compress js %}
{% block js %}{% endblock %}
{% endcompress %}

Other templates inherit from base.html and put the necessary scripts in the "js" block. However if there are no scripts on the page, django_compressor will still create an empty js file and put a script tag in the page.

**Comment by jezdez** [comment]
Fixed in c37dd377185ff5213f476f05579ff9299b5b92f7.
