### ISSUE TITLE
On Windows, normpath() creates backslashes instead of forward slashes

### ISSUE THREAD

**Issue by knabar** [mintchaos/django_compressor#16]
On Windows, os.path.normpath() creates backslashes, so some references to image URLs etc. in CSS files get mangled.

Changing the following line in filters\css_default.py seems to do the trick:

full_url = os.path.normpath(full_url)

to

full_url = os.path.normpath(full_url).replace('\', '/')

**Comment by carljm** [comment]
A better fix would be to import posixpath and use posixpath.normpath instead of os.path.normpath.

**Comment by jezdez** [comment]
Fixed in 7255025f11c54c0fee40578f1fb9eb11b22dc084.
