### ISSUE TITLE
Consider lxml support

### ISSUE THREAD

**Issue by mikl** [mintchaos/django_compressor#18]
[Benjamin Wohlwend](http://github.com/piquadrat) has done a couple of commit on his fork of django_compressor, using `lxml` in place of BeautifulSoup:
- piquadrat@c687d2fa7a1035f435a6f863f04e6e9ca8d8ef3c
- piquadrat@351c6b0891b9d320dfb4e53f40cc074b0435ec7e

I usually have lxml globally available on my servers, so having it as alternative to BS would be very nice, and it’s supposedly more efficient, given that it uses libxml and friends :)

**Comment by muhuk** [comment]
Benjamin's modifications replace lxml with BeautifulSoup. I think it would be better to provide it as an alternative.

First thing comes to my mind is some people might not be able to install/compile lxml on certain hostings.

**Comment by jezdez** [comment]
Agreed, using lxml would speed up the parsing dramatically, even though it isn't always available. So, I'm +1 on extracting the parsing to a separate function or find another way to use BeautifulSoup as a fallback.

**Comment by jezdez** [comment]
I've implemented a small parser API in jezdez/django_compressor@1298e2d573aeba1ce5d165465e91fa54133511a8 and added a LxmlParser, too.

**Comment by jezdez** [comment]
This has been added to master.
