### ISSUE TITLE
"ALLOWED_ARGS" doesn't exist. Line 95 of "compressor/templatetags/compress.py"

### ISSUE THREAD

**Issue by stormlifter** [mintchaos/django_compressor#19]
"ALLOWED_ARGS" doesn't exist. Line 95 of "compressor/templatetags/compress.py"

You're using a global variable there that doesn't exist. Causes an error when you use a tag that doesn't exist.

**Comment by muhuk** [comment]
I can confirm this. The change is done @ [90da0c1e](http://github.com/mintchaos/django_compressor/commit/90da0c1eea22f240a017780ee99947fe5f8ba6d7):

```
"%r's argument must be 'js' or 'css'." % (args[0], ', '.join(ALLOWED_ARGS))
```

`ALLOWED_ARGS` is undefined.

**Comment by muhuk** [comment]
I have a fix [here](http://github.com/muhuk/django_compressor/commit/f7ecd0da0e2009ffd205840a8f30b1690b99833e)
