### ISSUE TITLE
CSS Tidy seems to be broken.

### ISSUE THREAD

**Issue by stormlifter** [mintchaos/django_compressor#20]
I Have my settings set to.

```
COMPRESS_CSS_FILTERS = getattr(settings, 'COMPRESS_CSS_FILTERS', ['compressor.filters.csstidy.CSSTidyFilter'])
```

I have that set, no errors come up, but I look at the .css files generated in the 'CACHE' folder and there is nothing in the file.

Also is there a way to set: OUTPUT_DIR = getattr(settings, 'COMPRESS_OUTPUT_DIR', 'CACHE')
To just go to the default folder for media? I get "access denied" errors. Not sure why.

**Comment by jezdez** [comment]
The CSSTidy filter works for me. Just to be sure, do you have CSSTidy installed? You can download it here: http://csstidy.sourceforge.net/ 

Also, you only need to have something like this in your site's settings.py:

```
COMPRESS_CSS_FILTERS = ['compressor.filters.csstidy.CSSTidyFilter']
```

Regarding the OUTPUT_DIR, I've just fixed a bug in b2c4621aecdbfd454f4ea46ad0a887a4a6084cb9 that prevented to build the files in the media root.

**Comment by stormlifter** [comment]
Oops, gotta install that!

**Comment by stormlifter** [comment]
Wish there was a Python version of this thing, I have no clue how to install this nasty thing on my machine.

**Comment by jezdez** [comment]
FYI, on Ubuntu there is a package for it.

**Comment by sfllaw** [comment]
django-compressor should raise an exception when the csstiny binary is not found, or has a failed exit status in DEBUG mode.

In non-DEBUG mode, it should warn and spit out an unfiltered version.

**Comment by jezdez** [comment]
Agreed, that'd be a useful feature.
