### ISSUE TITLE
Compressor assumes XHTML in stylesheet import

### ISSUE THREAD

**Issue by EmilStenstrom** [mintchaos/django_compressor#22]
Hi,

I'm using HTML4 as my doctype for our site, something that does not allow stray slashes at the end of tags. As of now, compressor generates a slash at the end of <link />, something that gives us validation error on every page on our site.

I know, it's a minor issue, but it also has a very simple fix. Either add a COMPRESSOR_HTML_COMPLIANT = True option that removes the slash (while being fully backwards compliant), or allow us to override the default templates.

Thanks for some great code!

**Comment by beniwohli** [comment]
You can already override the [default templates](http://github.com/mintchaos/django_compressor/tree/master/compressor/templates/compressor/). Make a folder "compressor" in your project template folder and put your adapted templates there. Or am I missing something?

**Comment by EmilStenstrom** [comment]
Ehem, thanks :) I should have read the settings more carefully before posting an issue. Sorry!
