### ISSUE TITLE
[REQ] Inline images for browsers with data: URL support

### ISSUE THREAD

**Issue by ulope** [mintchaos/django_compressor#23]
It should be possible to (optionally) allow inlining of (background-)images for browsers with data: URL support.

**Comment by muhuk** [comment]
I have data URI inlining in [my fork](http://github.com/muhuk/django_compressor)

**Comment by ulope** [comment]
Good to know. 
How do you assure that only borwsers that support them get the data uri-fied result?

**Comment by muhuk** [comment]
I don't.
