### ISSUE TITLE
Potential dead-lock problem

### ISSUE THREAD

**Issue by ulope** [mintchaos/django_compressor#24]
In [/compressor/templatetags/compress.py#L32](http://github.com/mintchaos/django_compressor/blob/master/compressor/templatetags/compress.py#L32) anti dog-piling is implemented with a semi-busy loop waiting on a temporary cache key to be set to False.

This is a _REALLY BAD IDEA_ (TM).
If for some reason the other side of the condition fails to update the cache (and thereby doesn't remove "in_progress_key") you will have killed your whole site for 5 minutes (the lifetime of the temp. key) and additionally throttle your webserver with stagnant proceses/threads.

A IMHO better way to go about it would be to continue serving the old ( or uncompressed) value until the new one has been generated.

**Comment by jezdez** [comment]
I changed the anti-dog-piling mechanism to use the MintCache in 5efada444231fb7d947e44c58feb19f4e1e3ab88
