### ISSUE TITLE
YUI Issue

### ISSUE THREAD

**Issue by stormlifter** [mintchaos/django_compressor#25]
I downloaded YUI Compressor and put it in the filters folder in a folder called 'yui' but I'm getting an error that is caused by

```
        p = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.PIPE)
        p.stdin.write(self.content)
        p.stdin.close()
```

The error is IOError: [Errno 32] Broken pipe
   on p.stdin.write(self.content)

**Comment by stormlifter** [comment]
This is just a lack of a cleaner error. It really means to say that it can't find the file.

**Comment by jezdez** [comment]
Make sense, should probably raise a compressor.filters.FilterError

**Comment by stormlifter** [comment]
Yeah, the error really is just because it can't find the file so raising a better error would help someone in fixing the issue.

**Comment by emirotin** [comment]
Still an issue for me
When I have default settings for filters, everything works (and I see my files are really compressed). But when I set it to 

TOOLS_DIR = os.path.realpath(os.path.join(SITE_ROOT, '..', '..', 'tools'))
COMPRESS_CSS_FILTERS = ['compressor.filters.yui.YUICompressorFilter']
YUI_BINARY = 'java -jar ' + os.path.join(TOOLS_DIR, 'yuicompressor.jar')

It fails with Err 32.

<del>I assume it passes the relative path to the static file, which doesn't work whith YUIc residing in an external dir (like in my case)</del>

Checked with yuicompressor sitting next to settings.py - same error.

**Comment by emirotin** [comment]
UPD: well, looks like a wrong use of Popen with python 2.7:

```
>>> yuic = "java -jar /Users/eugenemirotin/Documents/workspace/django_compass_coffee/tools/yuicompressor.jar"
>>> import subprocess
>>> p = subprocess.Popen(yuic)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 672, in __init__
errread, errwrite)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1202, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
>>> import shlex
>>> p = subprocess.Popen(shlex.split(yuic))
```

Will test a bit more and probably put a pull request
