### ISSUE TITLE
Add cssmin filter

### ISSUE THREAD

**Issue by jezdez** [mintchaos/django_compressor#26]
Just wondering if we should add a css filter that uses the fabulous http://github.com/zacharyvoase/cssmin/ -- a port of the YUI CSS compressor. This would certainly lower the requirements and ease the installation (e.g. no Java required). Anyone any strong feelings against this?

**Comment by muhuk** [comment]
+1 for the filter.
-1 for bundling the lib.

**Comment by jezdez** [comment]
Agreed, the filter should check if it's able to import cssmin and raise a FilterError if not. In other words, I don't think it would be wise to install it as a dependency by default.
