### ISSUE TITLE
Fix reliance on storage backend being FileSystemStorage subclass

### ISSUE THREAD

**Issue by richleland** [mintchaos/django_compressor#27]
Right now if you set COMPRESS_STORAGE to a storage backend that does not subclass FileSystemStorage, an exception is thrown in the form of AttributeError. This is because compressor relies on the storage backend having a base_url attribute. I'll fork and work on a fix for this.

**Comment by jezdez** [comment]
Agreed, this is an unfortunate side effect.

**Comment by richleland** [comment]
I can get this to work if the source and destination files are both located within the custom storage, but want to take time to think about how to allow for separate input storage and output storage.

**Comment by richleland** [comment]
As an example - in my project I need compressor to read from local files but output compressed files to Rackspace Cloud Files.

**Comment by gvangool** [comment]
I just saw it as a requirement that the `Storage` class needed a `base_url` attribute.

So maybe, it should just be documented?

**Comment by jezdez** [comment]
Hm, yah, I would like to make this work for cloudfiles though, and wonder if we should add another storage option, that would allow compressor to write to a different storage backend than reading. OTOH, not sure if that would make it a bit clunky. Does anyone have a smart idea?

**Comment by kungpoo** [comment]
I just ran into this little annoyance. Did anyone get anywhere with it? Shame 'cause it's so damn cool.

**Comment by richleland** [comment]
Just looked over some changes I made locally a while back. Nothing worth committing. Like jezdez said removing the reliance on `base_url` would allow compressor to have different read/write locations. I personally just didn't get to a good solution in my experimentation but it's surely possible.

**Comment by wunki** [comment]
I replaced the dependency on `base_url` by looking at the `MEDIA_ROOT` settings. I tested it with django-storages S3 backend and all worked fine. 

The patch can be found here: [django-compressor-remove-base-url.patch](http://wunki.org/patches/django-compressor-remove-base-url.patch)

**Comment by jezdez** [comment]
Fixed as part of https://github.com/mintchaos/django_compressor/pull/59
