### ISSUE TITLE
import problems with cssmin filter

### ISSUE THREAD

**Issue by dcwatson** [mintchaos/django_compressor#28]
The cssmin filter does `import cssmin`, which may import `compressor.filters.cssmin` instead of the cssmin module, causing this error:

`AttributeError: 'module' object has no attribute 'cssmin'`

A simple but backwards-incompatible solution would be to just rename the cssmin filter.

**Comment by jezdez** [comment]
Hm, that's odd. which version of Python do you use?

**Comment by dcwatson** [comment]
Reproduced using 2.5 on linux, and 2.6 on Windows.

**Comment by jezdez** [comment]
Ok, thanks.

**Comment by jezdez** [comment]
Fixed in 4caa91fd9c700f92e597376fe02af8c2b4b886fe
