### ISSUE TITLE
media-files in app-directories...

### ISSUE THREAD

**Issue by gabor** [mintchaos/django_compressor#29]
hi,

i have app-specific javascript-files in the app's media subdirectory. is there a nice way to make those compress-able? originally i had a special view for the development-case, which served those media-files, but that did not work nicely with django-compressor. so i moved to an approach where i symlink all the app-specific media into the project-media-dir. is there a better solution?

**Comment by jezdez** [comment]
Personally I use http://pypi.python.org/pypi/django-staticfiles/ with django_compressor that allows you to build static media files from your apps and projects to a location and also ships with a file serving view for debugging.
