### ISSUE TITLE
css compressor can't handle non-ASCII characters in CSS files

### ISSUE THREAD

**Issue by carljm** [mintchaos/django_compressor#3]
This is necessary sometimes if you want, for instance, an em-dash in CSS-generated content.

**Comment by carljm** [comment]
Posted the relevant portion of the traceback at http://dpaste.de/BU3y/ (expires in a month)

**Comment by carljm** [comment]
Wow, this was hell to track down. It turns out the problem only shows up when a CSS file contains both a non-ASCII character and a URL. This is because the problem is actually triggered by the url_converter() callback in the URL absolutizer. It includes self.directory_name in the full_url it returns; self.directory_name is a unicode string, thus full_url becomes a unicode string, thus the re module tries to coerce the entire returned string into a unicode string (with the default ascii encoding), thus the error. Convert self.directory_name into a string, all the unicode conversion goes away, and so does the error.

Encoding insanity.

My fork contains the fix and a (now-passing) test.

**Comment by carljm** [comment]
And it turns out there were a couple similar fixes needed for the CSS media stuff. All the cases I've been able to find are now fixed.

**Comment by mintchaos** [comment]
Would it be better to switch it to use unicode strings everywhere instead of coercing into ascii? I wish I understood encoding stuff better.

**Comment by carljm** [comment]
You know, I thought of that. It seems like that's generally the way you're supposed to do things (use Unicode internally and encode/decode at the boundaries), but it also seems like the current approach has some advantages; it doesn't force you to figure out what encoding the files you are reading in use, you can just stay agnostic about that. As long as the stuff that matters to you (wrt splitting up HTML, CSS etc) is ASCII (and it pretty much has to be), it seems like this approach works.

Mostly, this was just easier to get working quickly :-)

**Comment by mintchaos** [comment]
So what happens to the em-dash when you ASCIIify the CSS file that contained it? 

I kinda feel like if I'm claiming utf-8 for my in my output tags I should probably attempt to keep unicode throughout the process. Shouldn't be too hard once I have some time to work on it again. For now I've made a note about this issue in the README and pointed at your branch for people who need it.

I totally understand the do the easiest thing to get it working approach.

**Comment by carljm** [comment]
The em-dash stays an em-dash. The byte-string is just a byte-string all the way through, nobody has to care what its encoding is if you never decode it to unicode, no assumption is made that it's ASCII or anything else. That's the downside of the convert-to-unicode approach; you have to somehow figure out what the proper encoding is to use to decode it to unicode, and if you get it wrong, you either get a UnicodeDecodeError or you screw up the data.

**Comment by carljm** [comment]
Yeah, I'm not convinced converting to unicode is the right approach here. Should compressor really be decoding and re-encoding everything to UTF-8, or should its output retain the original encoding of the input files, whatever that happens to be? I tend to think the latter.

**Comment by mintchaos** [comment]
You might be right. That's probably the route that'll do what's expected most of the time. I need to actually try your codes and throw some stuff at it.

**Comment by carljm** [comment]
This was fixed when my fork was merged.
