### ISSUE TITLE
switch off COMPRESS_REBUILD_TIMEOUT

### ISSUE THREAD

**Issue by romankrv** [mintchaos/django_compressor#30]
It is useful switch of this function, becouse not need regenerate media file even if not changes.
for example maybe additional parametr COMPRESS_REBUILD_TIMEOUT_OFF = True

PS
I don't understand what need COMPRESS_REBUILD_TIMEOUT if media not changes?

**Comment by jezdez** [comment]
This is needed because most of the cache backend behave differently when not passing a timeout value. In other words, we're bound to what the backend do, so have to provide a timeout. Set it very high and you're good.
