### ISSUE TITLE
Default timeout is set to greater than 30 days, which causes it to not get cached in memcached.

### ISSUE THREAD

**Issue by ara818** [mintchaos/django_compressor#32]
By default, the cache timeout for django-compressor is set to 
settings.REBUILD_TIMEOUT + settings.MINT_DELAY
Which is 2592000 + 30 = 2592030

The problem is, memcache's default max timeout is 30 days, and when you try to set a timeout greater than that, memcache treats the number as a unix timestamp which effectively sets the item expiration in the past and causes it to not get cached.

Details here: http://lzone.de/articles/memcached.htm (scroll to the bottom).

Here is the telnet out put of a memcache session. Notice that setting the timeout to 259200 is fine, but the minute we go over the item effectively isn't cached.

set django_compressor.69b2d4a4de1b-file 1 2592000 11
Hello world
STORED
get django_compressor.69b2d4a4de1b-file
VALUE django_compressor.69b2d4a4de1b-file 1 11
Hello world
END
set django_compressor.69b2d4a4de1b-file 1 2592030 11
Hello world
STORED
get django_compressor.69b2d4a4de1b-file
END

**Comment by carljm** [comment]
In Django 1.2 the memcached cache backend transparently handles this (http://code.djangoproject.com/browser/django/trunk/django/core/cache/backends/memcached.py#L26), so this is only a problem for pre-1.2 compatibility.

**Comment by jezdez** [comment]
It also got backported to 1.1.X in http://code.djangoproject.com/changeset/12412 and released in 1.1.2. Can you verify that this solves your issue?

**Comment by ara818** [comment]
I just upgraded to Django 1.2.1 and it definitely fixed the issue, so if the fix was backported than I'm sure it will work.

**Comment by jezdez** [comment]
Great, closing this because of that.
