### ISSUE TITLE
Spaces in path

### ISSUE THREAD

**Issue by derekr** [mintchaos/django_compressor#33]
Not sure if it's compressor or perhaps sass that is choking on this, but an exception is thrown in my template saying the file can't be found when there are spaces in the path.

<code>Caught Exception while rendering: Errno::ENOENT: No such file or directory - /Users/derek/Documents/Clients/Optimal/Open
  Use --trace for backtrace.</code>

**Comment by jezdez** [comment]
Hm, do you use any of the JavaScript or CSS filters?

**Comment by derekr** [comment]
None of the filters. Only the sass parser.

BUT!!! Good news: It was a missing symlink that I needed to create. I was thrown off by the exception message as it cut off at the first space. I assumed that was the root cause. Everything is working as is.

**Comment by jezdez** [comment]
Great, thanks!
