### ISSUE TITLE
Include models.py in compressor

### ISSUE THREAD

**Issue by shabda** [mintchaos/django_compressor#35]
Include an empty models.py with compressor or you will hit random bugs like this.

http://code.djangoproject.com/ticket/3310

**Comment by markstahler** [comment]
I dont think the solution is to add this to django_compressor but to wait for Django to issue to the fix.

**Comment by shabda** [comment]
Mark, I would disagree with that. We are not losing anything by including an empty models.py, and djangoa-dmin.py startapp creates an empty models.py, so deleting is an explicit decision, when we can go with the default.

Eg. presence of models.py is how you can differenciate between a python model and django app.

**Comment by jezdez** [comment]
Fixed in master, thx.
