### ISSUE TITLE
CssDataUriFilter should support IE < v8 better

### ISSUE THREAD

**Issue by peterlundberg** [mintchaos/django_compressor#38]
Using the UriFilter would be benificial, but becomes problematic when we need to support older browsers as well (notably IE7). One way would be to change CssDataUriFilter so it generates both

```
background-image: url(data:...);
*background-image: url(http:...);
```

Thus modern browsers will use the data url and IE7 will fallback and user the http url.

**Comment by peterlundberg** [comment]
Or even more advanced using mhtml which I found at http://www.phpied.com/mhtml-when-you-need-data-uris-in-ie7-and-under/

**Comment by kaj** [comment]
But the mhtml variant will result in all the images beeing included twice in the css file, which is a considerable bloat. Personally, I think IE7 users could live with some more separate file requests if that is the price for a smaller file for everyone else.

So if mthml support should be included, I think it should be optional.

**Comment by jezdez** [comment]
Sounds like a good idea, I would be happy to add that.

**Comment by EmilStenstrom** [comment]
Here's a correction to the above phpied article, with sample php code to translate into python: http://www.phpied.com/the-proper-mhtml-syntax/

**Comment by jezdez** [comment]
Closing in favor of https://github.com/jezdez/django_compressor/issues/10
