### ISSUE TITLE
Support relative urls in the css files to images

### ISSUE THREAD

**Issue by hvdklauw** [mintchaos/django_compressor#39]
Say I have a css file in the following path relative to the COMPRESS_URL

/css/style.css

In it I have a 

background: url(../img/icons/edit.png);

Statement.

This results into the images not being linked correctly because now it tries to find them in COMPRESS_URL/CACHE/img/icons/edit.png instead of COMPRESS_URL/img/icons/edit.png

**Comment by jezdez** [comment]
Hm, I can't reproduce this, and this seems well tested in http://github.com/mintchaos/django_compressor/blob/8de7eb0a8b9998ae579b/tests/core/tests.py#L138-181

Can you check if you have compressor.filters.css_default.CssAbsoluteFilter in your COMPRESS_CSS_FILTERS setting?

**Comment by hvdklauw** [comment]
I know the filter is in there.. because it didn't work.

I should have mentioned that I was using the latest stable release and I did see some things have changed.

Also I'm using in in combination with static files.
So the css might be in COMPRESS_URL/app_name/css/style.css
with the image in COMPRESS_URL/app_name/img/edit.png

The resulting css is in COMPRESS_URL/CACHE/ while the image stays in COMPRESS_URL/app_name/img/edit.png

**Comment by jezdez** [comment]
If you'd be able to provide a TestCase or some code, I'd be grateful.

**Comment by hvdklauw** [comment]
I'll have a look tomorrow.

**Comment by hvdklauw** [comment]
I have some testcode which does indeed not work with version 0.5.3 of compressor. 
It does however work correctly when I update to the source version from github.

So if you guys could release a new stable soon.. please do..so I can use it in production.

**Comment by jezdez** [comment]
Oh, that is a relief, will do soon indeed.
