### ISSUE TITLE
css filter munges data: urls

### ISSUE THREAD

**Issue by carljm** [mintchaos/django_compressor#4]
Images can be inlined into CSS using base64: url('data:image/png;base64,iVBORw.......')

Currently django_compressor munges these URLs, considering it a relative path and adding the media URL to it.

The fix is easy, and I've made it here: http://github.com/carljm/django_compressor/commit/1af352fcccb0cbeb3271dd9544b13c4c64a3286a

For now I fixed it by looking for URLs that start with data: -- I wonder though if there are other URL types other than http supported, and perhaps that check should be simplified to just look for any colon in the URL? Since colons aren't allowed in relative URL paths anyway.

**Comment by carljm** [comment]
This was fixed when my fork was merged.

**Comment by BradWhittington** [comment]
css compressor also munges https urls

**Comment by muhuk** [comment]
Both `data:` & `https:` URLs seem to work. This issue should be closed, no?

**Comment by jezdez** [comment]
Closing.
