### ISSUE TITLE
Cache doesn't work with mod_wsgi - recompiles with every request

### ISSUE THREAD

**Issue by jkbrzt** [mintchaos/django_compressor#40]
The cache seems to work fine when it's running in the Django's test server, but when it's running under mod_wsgi, then the result isn't cached and the CSS and JS get recompiled with every request (ignoring the cache configuration). 

Are there any requirements for the server configuration?

**Comment by jkbrzt** [comment]
Nevermind, I didn't realized that it relays on Django cache so you need to set CACHE_BACKEND to something that enables cross-process caching (memcached, file or db). I think this should be documented, though.

**Comment by jezdez** [comment]
Thanks, I added a section to the README.
