### ISSUE TITLE
(X)HTML rendering of css declaration

### ISSUE THREAD

**Issue by jjanssen** [mintchaos/django_compressor#41]
Currently the template for css_compress renders a XHTML declaration for a stylesheet:
<link rel="stylesheet" href="{{ url }}" ...... charset="utf-8" />

Is it possible to implement either a setting or detect the doctype to make it render like: 
<link rel="stylesheet" href="{{ url }}" ...... charset="utf-8"> without the trailing slash?

**Comment by beniwohli** [comment]
you can already do this by creating a folder compressor in your template directory and create (or copy and modify) [css.html](http://github.com/mintchaos/django_compressor/blob/master/compressor/templates/compressor/css.html) and [css_inline.html](http://github.com/mintchaos/django_compressor/blob/master/compressor/templates/compressor/css_inline.html).

**Comment by jjanssen** [comment]
Ah... ofcourse! I guess my morning started a little too early.

Thanks for the note!
