### ISSUE TITLE
Use a per-url mtime in CSS files instead of a global one

### ISSUE THREAD

**Issue by diox** [mintchaos/django_compressor#42]
Currently, when generating a CSS and rewriting URLs, css_default is appending the mtime of the CSS filename to each URL. This means that every modification of the css file will force a new version of the referenced urls in upstream and client caches.

It would be nice to have a setting that would make django_compressor use the get_mtime() function on each url, if it points to a local file, by checking MEDIA_URL. The relevant mtimes are probably already in the cache if the mtime_cache command was used.

**Comment by jezdez** [comment]
Interesting, that's a good idea. I'm only not sure if it requires a new settings, since it seems to me more like a bug than a different feature.

**Comment by diox** [comment]
I think it requires a setting because that would mean making much more get_mtime() calls, which are costly (would be nice to be able to use a multiget if we are using the cache, but I don't think it's trivial to implement). In my situation it's very well worth the overhead, but it might not apply to everyone. 

I'll try to work on a basic patch this week, unless someone beats me to it.

**Comment by diox** [comment]
I pushed a possible fix to my repository: 5b66048c03b10587f97d1ea59e36602e044e1e32

I would appreciate if someone proofreads it, I feel like it's more complicated than what it should be...

(edit: there was an extra print in my patch, corrected in  580a6a09dec0b39e44575000aa668af474bbc709 )

**Comment by jezdez** [comment]
Applied in jezdez@481633ea86b92fcc55708de26641eba503fa1ecf. Thanks!
