### ISSUE TITLE
JSMin removes IE conditional comments.

### ISSUE THREAD

**Issue by carljm** [mintchaos/django_compressor#48]
Apparently, there is such a thing as an IE conditional comment in JavaScript. (see http://robertnyman.com/2008/05/26/conditional-compilation-in-javascript/). I wouldn't particularly care, except that the very-handy Modernizr contains one.

The original JSMin, and the Python port by Baruch Even bundled with django_compressor and used as the default JS minifier, blithely strip out these conditional comments, thus breaking Modernizr on IE.

The ideal fix here would be to fix the bundled JSMin to leave these conditional comments alone. I think we would have to do that, since it's not clear that the Python JSMin is maintained anywhere else. 

Failing that, we should probably at least document the problem. FWIW, YUICompressor handles these conditional comments just fine.

**Comment by carljm** [comment]
There is this (http://pypi.python.org/pypi/jsmin) which claims (in comments in the actual code file) to be the same thing we're bundling but refactored for speed. It has not, however, been fixed to handle conditional comments; nor does it appear to have a bug tracker, home page, or source code repo anywhere.

**Comment by carljm** [comment]
The JS IE conditional comment  has been removed from more recent versions of Modernizr, so personally I'm once again in the camp of not particularly caring about them, and happily using JSMin (because having to fire up an external process and JVM so I can run YUICompressor is worse).

**Comment by jezdez** [comment]
Closing since I'm not sure how to handle this, really.
