### ISSUE TITLE
JS: Asign String over multiple lines

### ISSUE THREAD

**Issue by kraut** [mintchaos/django_compressor#50]
It seems that compressor does not like the follwing JS-Syntax.
I got UnterminatedStringLiteral Exceptio.

"Bad" JS Code:
var mystr= ' \
 string over  \
 multiple \
 lines ';

But this is working:
var mystr= '  '+
 'string over  '+
 'multiple '+
 'lines ';

Ive got the error while using facebox.js with compressor.

**Comment by jezdez** [comment]
Closing as worksforme, please reopen at the new home http://github.com/jezdez/django_compressor
