### ISSUE TITLE
Caught SuspiciousOperation while rendering: Attempted access to '/css/mystylesheet.css' denied.

### ISSUE THREAD

**Issue by nandoo** [mintchaos/django_compressor#51]
Hi,
i ran into an issue which might be a misconfiguration on my behalf. I have made the following entries into settings.py
COMPRESS = True
MEDIA_ROOT = '/var/www/repo/media/'

When trying to use the templatetag i get the following error:
Caught SuspiciousOperation while rendering: Attempted access to '/css/mystylesheet.css' denied.
The issue seems to come from:
    def get_filename(self, url):
        if not url.startswith(self.storage.base_url):
            raise UncompressableFileError('"%s" is not in COMPRESS_URL ("%s") and can not be compressed' % (url, self.storage.base_url))
        basename = url.replace(self.storage.base_url, "", 1)
        if not self.storage.exists(basename):
            raise UncompressableFileError('"%s" does not exist' % self.storage.path(basename))
        return self.storage.path(basename)

basename is just  '/css/mystylesheet.css' shouldn't it be /var/www/repo/media/css/mystylesheet.css?
Is there a setting I have missed?

Versions:
Django '1.3 alpha 1'
django_compressor version = "0.6a7"

**Comment by jezdez** [comment]
Can you check if you've set the MEDIA_URL setting, too?

**Comment by nandoo** [comment]
Yes i did.

**Comment by jezdez** [comment]
To what value if I may ask?

**Comment by nandoo** [comment]
Sorry didn't think this would be helpful, here it is
MEDIA_URL = 'http://www.example.com/repo/media/'

**Comment by TimothyFitz** [comment]
I ran into the same issue; the solution for me was to add trailing slashes to MEDIA_URL and MEDIA_ROOT. (Probably documented as required in Django, but since django_compressor was the first use of these for me I was unaware). Figured I'd leave this note here for anyone else googling the error.

**Comment by nandoo** [comment]
Thank you for that.

**Comment by jezdez** [comment]
Raise an exception if MEDIA_URL/COMPRESS_URL doesn&#39;t have a trailing slash. Closed by 403abc31d09c42e6d0f568c369e85edd079e39d4.
