### ISSUE TITLE
COMPRESS_URL and MEDIA_URL conflicts

### ISSUE THREAD

**Issue by statico** [mintchaos/django_compressor#55]
The short story is that setting `COMPRESS_URL` can produce incorrect URLs to assets.

Consider this scenario:
- During development, sometimes we serve assets via a path on the dev server, `/media/`, and other times we start our own static media server, `http://localhost:20123/media/`.
- Compressor requires that the URLs in `<script>` and `<link>` tags must begin with `MEDIA_URL` or `COMPRESS_URL`. Since the `MEDIA_URL` can change, tag URLs need to be relative, e.g., starting with `/media/`.
- If `COMPRESS_URL` is overridden to `/media/`, the generated links to the compressed bundles begins with `/media/`, which is incorrect if `MEDIA_URL` is still `http://localhost:20123/media/`.

This is a showstopper, unfortunately, and I'm not sure what to do here.

**Comment by statico** [comment]
Ahhh, my mistake. _The URLs in the templates should begin with `{{ MEDIA_URL }}`._ This should probably be fixed in the documentation.

**Comment by jezdez** [comment]
Fixed where exactly?
