### ISSUE TITLE
CSSMinFilter doesn't change relative path

### ISSUE THREAD

**Issue by pheze** [mintchaos/django_compressor#61]
With the default css filter, ../imgs/test.png is changed to /media/imgs/test.png, but with CSSMinFilter, it is not changed. It means that it tries to get: ../imgs/test.png from /media/CACHE/css/.. instead of /media/css/... which means that all images aren't found. 

I wanted to create a patch but I wasn't sure if the right way to do it would have been to change cssmin.py or to change how the parsing is done and change it there before cssmin.py does the minify.

**Comment by jezdez** [comment]
First, which version of compressor are you running?
Secondly, can you confirm that your `COMPRESS_CSS_FILTERS` setting looks like this: `COMPRESS_CSS_FILTERS = ['compressor.filters.css_default.CssAbsoluteFilter', 'compressor.filters.cssmin.CSSMinFilter']` ?

**Comment by jezdez** [comment]
Closing as worksforme, please reopen at the new home http://github.com/jezdez/django_compressor
