### ISSUE TITLE
Documentation improvement needed. (Please add INSTALLATION section)

### ISSUE THREAD

**Issue by pipoket** [mintchaos/django_compressor#64]
I think the documentation should address the following.
- Add following line to the INSTALLED_APPS on your settings.py:
  
  ```
  INSTALLED_APPS = (
      ...
      'compressor',
      ...
  )
  ```

And... yes, the django_compressor itself is so simple and great to use(seriously, thx a lot!) but it would be better if there were some kind of `INSTALLATION` section in documentation.

**Comment by jezdez** [comment]
Agreed, which is why I traveled back in time and added it: http://django_compressor.readthedocs.org/en/latest/#installation :)
