### ISSUE TITLE
need package_data so templates are installed from tarball via easy_install or pip

### ISSUE THREAD

**Issue by carljm** [mintchaos/django_compressor#7]
setup.py is missing the package_data argument. fixed here: http://github.com/carljm/django_compressor/commit/22909c9186b631f1ebe6338a615f3f6ce6ef8f41

**Comment by mintchaos** [comment]
I had three pull requests of this same thing. I grabbed benspaulding's It's fixed in my master as of c5adc4276c. Thanks for your work!
