### ISSUE TITLE
Missing files (js or css) should be skipped/fail silently

### ISSUE THREAD

**Issue by shabda** [mintchaos/django_compressor#8]
If a js/css file is missing the rest of page will be displayes in the html. This should be the default behaviour of the compressor. Currently it leads to 500 errors on missing files.

**Comment by carljm** [comment]
Here's one solution: http://github.com/carljm/django_compressor/commit/9d55c6a6ffd18b077991fef9f4545696a50dd943

Still raises an error (UncompressableFileError) if DEBUG is on, passes silently when DEBUG is off.

**Comment by carljm** [comment]
This was fixed when my fork was merged, but I guess I can't close it since I didn't open it.

**Comment by shabda** [comment]
closing. :)
