### ISSUE TITLE
Default CSS filters should be overridable.

### ISSUE THREAD

**Issue by carljm** [mintchaos/django_compressor#9]
I have a case where I need to modify the relative-absolute path-hacking in CSS for certain types of url() links (cross-domain restrictions on web fonts). By far the most straightforward (and performant) way to do this is to subclass CssAbsoluteFilter and modify its behavior slightly... but at the moment, there's no way (short of ugly monkeypatching) to actually replace CssAbsoluteFilter in the CSS filters list with my modified version.  

I think that there should be no required CSS filters, instead the two default filters should simply be the default value of the COMPRESS_CSS_FILTERS setting. I realize this makes it easier to break things by overriding incorrectly, but I think that tradeoff is worth it to provide more flexibility.

I realize this would be backwards-incompatible for anyone already overriding COMPRESS_CSS_FILTERS. Not sure what the best way to deal with that would be. Anyway, this change is in my fork.

**Comment by carljm** [comment]
This change is in a reset_default_css_filters branch: http://github.com/carljm/django_compressor/tree/reset_default_css_filters

**Comment by mintchaos** [comment]
I agree with this change. It's what it should have been in the first place. This'll happen at some point.

**Comment by jezdez** [comment]
I'm inclined to make this change rather now than later, if you'd be ok with it.

**Comment by jezdez** [comment]
Fixed in 3be00046d4f997526fa8cb370e85358aea68bd5d.
